version: '3.9'

services:
  db:
    image: postgres
    container_name: notebook_test_db
    restart: always
    ports:
      - "3008:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root